name: $(Date:yyyyMMdd).$(Rev:r).$(Build.BuildId)

trigger: none
pr: none

variables:
  artifact_name: banking-service-ms

stages:
  - stage: BUILD
    displayName: "Build BankingServiceMs Microservice"
    jobs:
    - job: Build
      displayName: Build BankingServiceMs Microservice
      steps:
        - template: /homeFolder/devops/pipeline-templates/ms-build-steps-template.yaml
          parameters:
            solutionFolder: "homeFolder/soln/"
            repositoryName: "app-innovation/hexagonal"
            dockerfilePath: "homeFolder/devops/Dockerfile"
            helmChartPath: "homeFolder/devops/nodejsapp"
            valuePath: "homeFolder/devops/ci"
            artifactTag: "latest-artifact-build"
            contextPath: "homeFolder/soln/"
            crServiceConnection: "github-registry"

  - stage: RELEASE
    displayName: "Deploy BankingServiceMs Microservice"
    variables:
      ms_release: "banking-service-ms-release-v1"
    jobs:
    
